"""
Covers scripts/lib/patch_compose_for_https.py, which
scripts/setup-https-selfsigned.sh and scripts/setup-https-letsencrypt.sh
both use to strip direct port exposure from docker-compose.yml and add
an nginx service in front of it.

This is exact-string-match based (not a real YAML merge), which means it
can silently do nothing if docker-compose.yml's structure drifts from
what it expects -- these tests run the actual patcher against the
project's real, current docker-compose.yml specifically so a future
docker-compose.yml edit that breaks the match gets caught here, not
discovered by someone running the script against a production host and
ending up with postgres/redis/api still directly exposed to the internet.

The actual nginx config files (deploy/nginx/nginx.conf, generated by the
shell scripts, not this module) and the Let's Encrypt HTTP-01 flow
itself can't be verified in this environment -- no docker or nginx
binary available, and no real internet-facing host to complete an ACME
challenge against. That part was reviewed carefully by hand instead
(cross-checked against frontend/nginx.conf's already-working WebSocket
header pattern) but isn't proven the way the tests below are.
"""
import importlib.util
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
REAL_COMPOSE_FILE = PROJECT_ROOT / "docker-compose.yml"
PATCHER_PATH = PROJECT_ROOT / "scripts" / "lib" / "patch_compose_for_https.py"


def _load_patcher():
    spec = importlib.util.spec_from_file_location("patch_compose_for_https", PATCHER_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules["patch_compose_for_https"] = module
    spec.loader.exec_module(module)
    return module


def test_patcher_matches_the_projects_real_docker_compose_without_warnings(capsys):
    patcher = _load_patcher()

    with tempfile.TemporaryDirectory() as tmp:
        compose_copy = Path(tmp) / "docker-compose.yml"
        shutil.copy(REAL_COMPOSE_FILE, compose_copy)

        nginx_service = "\n  nginx:\n    image: nginx:1.27-alpine\n"
        patcher.patch(compose_copy, nginx_service)

        captured = capsys.readouterr()
        assert "WARNING" not in captured.out, (
            f"patch_compose_for_https.py didn't match the project's real "
            f"docker-compose.yml -- something is still directly exposed:\n{captured.out}"
        )

        import yaml

        doc = yaml.safe_load(compose_copy.read_text())
        for service in ("postgres", "redis", "api"):
            assert "ports" not in doc["services"][service], f"{service} is still directly port-exposed"
        assert "ports" not in doc["services"]["frontend"]
        assert doc["services"]["frontend"]["expose"] == ["80"]
        assert "nginx" in doc["services"]


def test_patcher_is_idempotent_about_not_duplicating_nginx_service():
    """Running the patcher twice (e.g. re-running the setup script) must
    not add a second nginx: service block."""
    patcher = _load_patcher()

    with tempfile.TemporaryDirectory() as tmp:
        compose_copy = Path(tmp) / "docker-compose.yml"
        shutil.copy(REAL_COMPOSE_FILE, compose_copy)

        nginx_service = "\n  nginx:\n    image: nginx:1.27-alpine\n"
        patcher.patch(compose_copy, nginx_service)
        text_after_first = compose_copy.read_text()
        patcher.patch(compose_copy, nginx_service)
        text_after_second = compose_copy.read_text()

        assert text_after_first.count("\n  nginx:\n") == 1
        assert text_after_second.count("\n  nginx:\n") == 1


def test_letsencrypt_certbot_service_also_gets_inserted():
    patcher = _load_patcher()

    with tempfile.TemporaryDirectory() as tmp:
        compose_copy = Path(tmp) / "docker-compose.yml"
        shutil.copy(REAL_COMPOSE_FILE, compose_copy)

        nginx_and_certbot = (
            "\n  nginx:\n    image: nginx:1.27-alpine\n"
            "\n  certbot:\n    image: certbot/certbot:latest\n"
        )
        patcher.patch(compose_copy, nginx_and_certbot)

        import yaml

        doc = yaml.safe_load(compose_copy.read_text())
        assert "nginx" in doc["services"]
        assert "certbot" in doc["services"]


def test_all_https_setup_scripts_have_valid_shell_syntax():
    scripts_dir = PROJECT_ROOT / "scripts"
    for name in ("setup-https-selfsigned.sh", "setup-https-letsencrypt.sh", "renew-https-certs.sh"):
        path = scripts_dir / name
        assert path.exists(), f"{name} is missing"
        result = subprocess.run(["bash", "-n", str(path)], capture_output=True, text=True)
        assert result.returncode == 0, f"{name} has a shell syntax error:\n{result.stderr}"


def test_selfsigned_and_letsencrypt_nginx_configs_both_forward_websocket_upgrade_headers():
    """The bug this whole thing started from: the outer (TLS-terminating)
    nginx has to forward Upgrade/Connection itself, or the
    deployment-progress WebSocket breaks even though the frontend's own
    inner nginx (frontend/nginx.conf) sets these correctly -- a proxy
    chain is only as good as its weakest hop."""
    for script_name in ("setup-https-selfsigned.sh", "setup-https-letsencrypt.sh"):
        script_text = (PROJECT_ROOT / "scripts" / script_name).read_text()
        assert "proxy_set_header Upgrade" in script_text, f"{script_name} is missing the WebSocket Upgrade header"
        assert 'proxy_set_header Connection "upgrade"' in script_text, (
            f"{script_name} is missing the WebSocket Connection header"
        )
